# This is an example of a job that runs when a branch or tag  is deleted.
# One can use a workflow like this to clean up any environments or
# intermediate artifacts maintained for each branch/tag.
#
# If lots of tags are deleted at once, then this workflow may not run.
# For this reason, the workflow can also be triggered manually via the
# 'workflow_dispatch' trigger.
#
# Also note if the workflow is triggered by 'delete', then the deleted
# branch cannot be accessed, and the version of the workflow in the default
# branch will be executed.
#
# The branch name is accessed differently depending on the workflow trigger.
# If triggered by the 'delete' event, then the deleted branch is stored in
# github.event.ref. If triggered by the 'workflow_trigger' event, then the
# branch is passed as an input to the workfow as 'inputs.branch_name'.

name: Cleanup
run-name: Cleanup branch '${{ inputs.branch_name || github.event.ref }}'
on:
  delete:
  workflow_dispatch:
    inputs:
      branch_name:
        description: Name of the branch to clean up
        type: string
        required: true
      force:
        description: Allow cleanup of 'main' and 'release/**' branches
        type: boolean
        required: false
        default: false        
jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    if: |
      inputs.force ||
      ((inputs.branch_name || github.event.ref) != 'main') &&
      (!contains((inputs.branch_name || github.event.ref), 'release'))
    steps:
      - name: Print branch name
        run: echo Cleaning up branch ${{ inputs.branch_name || github.event.ref }}
      - name: Write summary
        run: echo "# Cleaned up '${{ inputs.branch_name || github.event.ref }}'" >$GITHUB_STEP_SUMMARY
