name: Contexts
on:
  delete:
  pull_request:
  push:
  workflow_call:
  workflow_dispatch:
jobs:
  print_contexts:
    name: Print Contexts
    runs-on: ubuntu-latest
    steps:
      - name: Print contexts
        run: |
          echo ${{ github }} | jq .
          echo env: ${{ env }} | jq .
          echo vars: ${{ vars }} | jq .
          echo job: ${{ job }} | jq .
          echo steps: ${{ steps }} | jq .
          echo runner: ${{ runner }} | jq .
          echo inputs: ${{ inputs }} | jq .
          
