name: Contexts
on:
  delete:
  pull_request:
  push:
  workflow_call:
  workflow_dispatch:
jobs:
  print_contexts:
    name: Print Contexts
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        run: |
          cat << endOfContext
          ${{ toJSON(github) }}
          endOfContext
      - name: Print env context
        run: |
          cat << endOfContext
          ${{ toJSON(env) }}
          endOfContext
