name: Contexts
on:
  delete:
  pull_request:
  push:
  workflow_call:
  workflow_dispatch:
jobs:
  print_contexts:
    name: Print Contexts
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        run: |
          : <<'END_COMMENT'
          These are the contents of the 'github' context:
          -----------------------------------------------
          ${{ toJSON(github) }}
          END_COMMENT
